# Generated by Django 4.2 on 2023-04-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Proveedor',
                'verbose_name_plural': 'Categorias de Proveedor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numero de Telefono')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del Proveedor')),
                ('category', models.ManyToManyField(to='backend.suppliercategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
    ]
