# Generated by Django 4.2 on 2023-04-15 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en el formato: '88888888'. 8 dígitos permitidos.", regex='^\\+?1?\\d{8,8}$')], verbose_name='Numero de Telefono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe estar en el formato: '88888888'. 8 dígitos permitidos.", regex='^\\+?1?\\d{8,8}$')], verbose_name='Numero de Telefono'),
        ),
    ]
